name: Clear Cloudflare Cache After Pages Deployment

on: page_build

jobs:
    clear_cloudflare_cache:
        runs-on: ubuntu-latest
        steps:
            - name: Purge Cloudflare cache
              env:
                  CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
                  CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
              run: |
                  curl -X POST "https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_ZONE}/purge_cache" \
                       -H "Authorization: Bearer ${CLOUDFLARE_TOKEN}" \
                       -H "Content-Type: application/json" \
                       --data '{"files":["https://cdn.adsgrab.com/scripts/player.min.js"]}'
